user root;
worker_processes 1;
pid ${WEBTEST_DIR:-$HOME/webtest-work}/nginx.pid;
error_log ${WEBTEST_DIR:-$HOME/webtest-work}/logs/error.log;
events { worker_connections 256; }
http {
  access_log ${WEBTEST_DIR:-$HOME/webtest-work}/logs/access.log;
  client_body_temp_path ${WEBTEST_DIR:-$HOME/webtest-work}/tmp; proxy_temp_path ${WEBTEST_DIR:-$HOME/webtest-work}/tmp; fastcgi_temp_path ${WEBTEST_DIR:-$HOME/webtest-work}/tmp; uwsgi_temp_path ${WEBTEST_DIR:-$HOME/webtest-work}/tmp; scgi_temp_path ${WEBTEST_DIR:-$HOME/webtest-work}/tmp;
  map $http_upgrade $connection_upgrade { default upgrade; '' close; }
  gzip on;
  include ${WEBTEST_DIR:-$HOME/webtest-work}/config/nginx/proxy-confs/*.subdomain.conf;
}
