import json
def B(): return json.loads(ev('Module.ccall("sevendays_test_base","string",[],[])'))
def S(): return json.loads(ev('Module.ccall("sevendays_test_state","string",[],[])'))
def gather(m,a,k): ev('Module.ccall("sevendays_test_gather",null,["number","number","number"],[%d,%d,%d])'%(m,a,k))
def craft(r): return ev('Module.ccall("sevendays_test_craft","number",["string"],["%s"])'%r)
raid('gohma'); raid('sword'); time.sleep(0.5)
k=int(time.time())
for m,a in ((0,20),(2,20),(4,10),(3,5),(1,5)): gather(m,a,k+m); time.sleep(0.3)
time.sleep(1); print('pool',S())
print('craft scarecrow',craft('scarecrow')); time.sleep(1); print('craft guardbaba',craft('guardbaba')); time.sleep(1)
print('after',S())
raid('warp:211'); time.sleep(10)
b=B(); print({k:b.get(k) for k in ('scene','link','owner','placeableActors','dyna')}); print(json.dumps(b.get('pieces',b))[:1500])
shot('/tmp/m10ev/vq-kokiri.png')
